<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>deltabox</ToolCommandName>

    <PackageId>DeltaBox</PackageId> 
    <Version>1.0.0</Version>
    <Authors>Kaiky</Authors>
    <Company>Kaiky</Company>
    <Description>CLI para gerenciamento DeltaBox</Description>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="LibGit2Sharp" Version="0.31.0" />
  </ItemGroup>

</Project>
